version: "3.8"
services:
  wg-easy:
    environment:
      - PUID=1000
      - PGID=33
      - WG_HOST=3.8.39.23
      - PASSWORD=obviamente_noes
      - WG_DEFAULT_DNS=192.168.1.100 # Cambia esto por la IP interna del servidor DNS
    image: weejewel/wg-easy
    container_name: wg-easy
    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

  dns-server:
    image: pihole/pihole
    container_name: pihole
    environment:
      TZ: 'Europe/Madrid'
      WEBPASSWORD: 'otra_contraseña'
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80"
      - "443:443"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
